apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30095
