apiVersion: v1
kind: Service
metadata:
  name: kiali-nodeport
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
  ports:
    - protocol: TCP
      port: 20001
      targetPort: 20001
      nodePort: 30094
